version: '3'
services:
# cada container:
  redis: #servidor de mensagens pub sub
    image: redis:latest
    ports:
      - "6379:6379"

  servidor:
    build: .
    command: node servidor.js
    depends_on:
      - redis

  cliente1:
    build: .
    environment:
      - NOME=Kaka
      - LANCE=10
    depends_on:
      - redis

  cliente2:
    build: .
    environment:
      - NOME=Camila
      - LANCE=150
    depends_on:
      - redis

  cliente3:
    build: .
    environment:
      - NOME=Maria Bessa
      - LANCE=180000
    depends_on:
      - redis
