apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servidor
  template:
    metadata:
      labels:
        app: servidor
    spec:
      containers:
        - name: servidor
          image: camilaapa/redis_app:latest
          command: ["node", "servidor.js"]
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: servidor
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
  selector:
    app: servidor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: cliente
          image: camilaapa/redis_app:latest
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: APP_SCRIPT
              value: cliente.js
---
apiVersion: v1
kind: Service
metadata:
  name: cliente
spec:
  type: ClusterIP
  selector:
    app: cliente
  ports:
    - port: 80
      targetPort: 3000
