apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servidor
  template:
    metadata:
      labels:
        app: servidor
    spec:
      containers:
      - name: servidor
        image: camilaapa/redis_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_SENTINEL_QUORUM
          value: "2"  
        - name: REDIS_SENTINEL_RETRY_STRATEGY
          value: "1000"  
        - name: REDIS_SENTINEL_HOST
          value: "redis-sentinel"
        - name: REDIS_SENTINEL_PORT
          value: "26379"
        - name: REDIS_MASTER_NAME
          value: "mymaster"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        command: ["node", "servidor.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: servidor
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: servidor